export const APP_CONFIG = {
  name: 'Saarth Holidays',
  tagline: "Chhattisgarh's Best Travel Agency",
  description: 'Book flights, hotels, and holiday packages from Chhattisgarh to anywhere in the world',
  contact: {
    phone: '+91 98765 43210',
    email: 'info@saarthholidays.com',
    address: 'Raipur, Chhattisgarh, India',
    whatsapp: '+919876543210',
  },
  social: {
    facebook: 'https://facebook.com/saarthholidays',
    instagram: 'https://instagram.com/saarthholidays',
    twitter: 'https://twitter.com/saarthholidays',
  },
}

export const AIRPORTS = {
  RAIPUR: {
    code: 'RPR',
    name: 'Swami Vivekananda Airport',
    city: 'Raipur',
    state: 'Chhattisgarh',
  },
  DELHI: { code: 'DEL', name: 'Indira Gandhi International', city: 'New Delhi' },
  MUMBAI: { code: 'BOM', name: 'Chhatrapati Shivaji Maharaj', city: 'Mumbai' },
  BANGALORE: { code: 'BLR', name: 'Kempegowda International', city: 'Bangalore' },
  HYDERABAD: { code: 'HYD', name: 'Rajiv Gandhi International', city: 'Hyderabad' },
  KOLKATA: { code: 'CCU', name: 'Netaji Subhas Chandra Bose', city: 'Kolkata' },
}

export const POPULAR_DESTINATIONS = [
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    continent: 'Europe',
    airportCode: 'AMS',
    image: '/images/amsterdam.jpg',
    price: 150000,
    currency: 'INR',
    description: 'Canals, Museums & Tulips',
    duration: '7 days',
    highlights: ['Anne Frank House', 'Van Gogh Museum', 'Canal Cruise', 'Keukenhof Gardens'],
  },
  {
    id: 'ayodhya',
    name: 'Ayodhya',
    country: 'India',
    continent: 'Asia',
    airportCode: 'AYJ',
    image: '/images/ayodhya.jpg',
    price: 25000,
    currency: 'INR',
    description: 'Spiritual Journey',
    duration: '3 days',
    highlights: ['Ram Mandir', 'Hanuman Garhi', 'Kanak Bhawan', 'Saryu River Aarti'],
  },
  {
    id: 'kerala',
    name: 'Kerala',
    country: 'India',
    continent: 'Asia',
    airportCode: 'COK',
    image: '/images/kerala.jpg',
    price: 35000,
    currency: 'INR',
    description: 'Backwaters & Beaches',
    duration: '5 days',
    highlights: ['Houseboat Stay', 'Munnar Tea Gardens', 'Alleppey Backwaters', 'Fort Kochi'],
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    continent: 'Asia',
    airportCode: 'DXB',
    image: '/images/dubai.jpg',
    price: 80000,
    currency: 'INR',
    description: 'Luxury & Adventure',
    duration: '5 days',
    highlights: ['Burj Khalifa', 'Desert Safari', 'Dubai Mall', 'Palm Jumeirah'],
  },
  {
    id: 'goa',
    name: 'Goa',
    country: 'India',
    continent: 'Asia',
    airportCode: 'GOI',
    image: '/images/goa.jpg',
    price: 20000,
    currency: 'INR',
    description: 'Sun, Sand & Party',
    duration: '4 days',
    highlights: ['Beach Hopping', 'Water Sports', 'Nightlife', 'Portuguese Churches'],
  },
  {
    id: 'thailand',
    name: 'Thailand',
    country: 'Thailand',
    continent: 'Asia',
    airportCode: 'BKK',
    image: '/images/thailand.jpg',
    price: 60000,
    currency: 'INR',
    description: 'Temples & Islands',
    duration: '6 days',
    highlights: ['Grand Palace', 'Phi Phi Islands', 'Floating Market', 'Thai Massage'],
  },
]

export const API_ENDPOINTS = {
  AMADEUS_AUTH: 'https://test.api.amadeus.com/v1/security/oauth2/token',
  AMADEUS_FLIGHT_SEARCH: 'https://test.api.amadeus.com/v2/shopping/flight-offers',
  AMADEUS_AIRPORT_SEARCH: 'https://test.api.amadeus.com/v1/reference-data/locations',
  OPENWEATHER: 'https://api.openweathermap.org/data/2.5',
  EXCHANGE_RATE: 'https://api.exchangerate-api.com/v4/latest',
}